project:
  type: website
  output-dir: docs

website:
  title: "Kailyn Hogan's DSPG Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lumen
    css: styles.css

editor: visual
