project:
  type: website
  output-dir: docs

website:
  title: "Kailyn Hogan's DSPG Blog"
  navbar:
    background: "#C8102E"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kailynhogan
      - icon: linkedin
        href: https://www.linkedin.com/in/kailynjhogan/
format:
  html:
    css: styles.css

editor: visual
