---
title: "Guide: API Variable Codes"
author: "Kailyn Hogan"
date: "2023-07-12"
categories: [Week Nine, Guide, R, Demographic Analysis]
---

The API variable codes listed on this page were used in the demographic analysis I conducted for the 2021 AI Housing Project for Data Science for the Public Good. The API variable codes are organized in tables by variable name and API code and further separate by survey type.

*Decennial Census*

| Variable               | API Code |
|------------------------|----------|
| Total Population, 2000 | P001001  |
| Total Population, 2010 | P001001  |
| Total Population, 2020 | P1_001N  |

*5-Year American Community Survey - Age Variables*

| Variable                                | API Code   |
|-----------------------------------------|------------|
| Median Age                              | B01002_001 |
| Total Population by Age and Sex, Male   | B01001_002 |
| Under 5, Male                           | B01001_003 |
| 5 to 9, Male                            | B01001_004 |
| 10 to 14, Male                          | B01001_005 |
| 15 to 17, Male                          | B01001_006 |
| 65 to 66, Male                          | B01001_020 |
| 67 to 69, Male                          | B01001_021 |
| 70 to 74, Male                          | B01001_022 |
| 75 to 79, Male                          | B01001_023 |
| 80 to 84, Male                          | B01001_024 |
| Over 85, Male                           | B01001_025 |
| Total Population by Age and Sex, Female | B01001_026 |
| Under 5, Female                         | B01001_027 |
| 5 to 9, Female                          | B01001_028 |
| 10 to 14, Female                        | B01001_029 |
| 15 to 17, Female                        | B01001_030 |
| 65 to 66, Female                        | B01001_044 |
| 67 to 69, Female                        | B01001_045 |
| 70 to 74, Female                        | B01001_046 |
| 75 to 79, Female                        | B01001_047 |
| 80 to 84, Female                        | B01001_048 |
| Over 85, Female                         | B01001_049 |

*5-Year American Community Survey - Housing Variables*

| Variable              | API Code   |
|-----------------------|------------|
| Total Housing Units   | B25001_001 |
| Occupied Units        | B25002_002 |
| Owner Occupied Units  | B25003_002 |
| Renter Occupied Units | B25003_003 |
| Vacant Units          | B25002_003 |
| Median Home Value     | B25077_001 |
| Median Year Built     | B25035_001 |

*5-Year American Community Survey - Workforce Variables*

| Variable                                            | API Code   |
|-----------------------------------------------------|------------|
| Median Income                                       | B19013_001 |
| Total Labor Force by Commute                        | B08008_001 |
| Commute to Work                                     | B08008_004 |
| Total Labor Force                                   | B23001_001 |
| Total Labor Force, Male                             | B23001_002 |
| Total Labor Force 16 to 19, Male                    | B23001_003 |
| Total Labor Force 16 to 19, In Armed Forces, Male   | B23001_005 |
| Total Labor Force 16 to 19, Employed, Male          | B23001_007 |
| Total Labor Force 16 to 19, Unemployed, Male        | B23001_008 |
| Total Labor Force 20 to 21, Male                    | B23001_010 |
| Total Labor Force 20 to 21, In Armed Forces, Male   | B23001_012 |
| Total Labor Force 20 to 21, Employed, Male          | B23001_014 |
| Total Labor Force 20 to 21, Unemployed, Male        | B23001_015 |
| Total Labor Force 22 to 24, Male                    | B23001_017 |
| Total Labor Force 22 to 24, In Armed Forces, Male   | B23001_019 |
| Total Labor Force 22 to 24, Employed, Male          | B23001_021 |
| Total Labor Force 22 to 24, Unemployed, Male        | B23001_022 |
| Total Labor Force 25 to 29, Male                    | B23001_024 |
| Total Labor Force 25 to 29, In Armed Forces, Male   | B23001_026 |
| Total Labor Force 25 to 29, Employed, Male          | B23001_028 |
| Total Labor Force 25 to 29, Unemployed, Male        | B23001_029 |
| Total Labor Force 30 to 34, Male                    | B23001_031 |
| Total Labor Force 30 to 34, In Armed Forces, Male   | B23001_033 |
| Total Labor Force 30 to 34, Employed, Male          | B23001_035 |
| Total Labor Force 30 to 34, Unemployed, Male        | B23001_036 |
| Total Labor Force 35 to 44, Male                    | B23001_038 |
| Total Labor Force 35 to 44, In Armed Forces, Male   | B23001_040 |
| Total Labor Force 35 to 44, Employed, Male          | B23001_042 |
| Total Labor Force 35 to 44, Unemployed, Male        | B23001_043 |
| Total Labor Force 45 to 54, Male                    | B23001_045 |
| Total Labor Force 45 to 54, In Armed Forces, Male   | B23001_047 |
| Total Labor Force 45 to 54, Employed, Male          | B23001_049 |
| Total Labor Force 45 to 54, Unemployed, Male        | B23001_050 |
| Total Labor Force 55 to 59, Male                    | B23001_052 |
| Total Labor Force 55 to 59, In Armed Forces, Male   | B23001_054 |
| Total Labor Force 55 to 59, Employed, Male          | B23001_056 |
| Total Labor Force 55 to 59, Unemployed, Male        | B23001_057 |
| Total Labor Force 60 to 61, Male                    | B23001_059 |
| Total Labor Force 60 to 61, In Armed Forces, Male   | B23001_061 |
| Total Labor Force 60 to 61, Employed, Male          | B23001_063 |
| Total Labor Force 60 to 61, Unemployed, Male        | B23001_064 |
| Total Labor Force 62 to 64, Male                    | B23001_066 |
| Total Labor Force 62 to 64, In Armed Forces, Male   | B23001_068 |
| Total Labor Force 62 to 64, Employed, Male          | B23001_070 |
| Total Labor Force 62 to 64, Unemployed, Male        | B23001_071 |
| Total Labor Force 65 to 69, Male                    | B23001_073 |
| Total Labor Force 65 to 69, Employed, Male          | B23001_075 |
| Total Labor Force 65 to 69, Unemployed, Male        | B23001_076 |
| Total Labor Force 70 to 74, Male                    | B23001_078 |
| Total Labor Force 70 to 74, Employed, Male          | B23001_080 |
| Total Labor Force 70 to 74, Unemployed, Male        | B23001_081 |
| Total Labor Force Over 75, Male                     | B23001_083 |
| Total Labor Force Over 75, Employed, Male           | B23001_085 |
| Total Labor Force Over 75, Unemployed, Male         | B23001_086 |
| Total Labor Force, Female                           | B23001_088 |
| Total Labor Force 16 to 19, Female                  | B23001_089 |
| Total Labor Force 16 to 19, In Armed Forces, Female | B23001_091 |
| Total Labor Force 16 to 19, Employed, Female        | B23001_093 |
| Total Labor Force 16 to 19, Unemployed, Female      | B23001_094 |
| Total Labor Force 20 to 21, Female                  | B23001_096 |
| Total Labor Force 20 to 21, In Armed Forces, Female | B23001_098 |
| Total Labor Force 20 to 21, Employed, Female        | B23001_099 |
| Total Labor Force 20 to 21, Unemployed, Female      | B23001_101 |
| Total Labor Force 22 to 24, Female                  | B23001_103 |
| Total Labor Force 22 to 24, In Armed Forces, Female | B23001_105 |
| Total Labor Force 22 to 24, Employed, Female        | B23001_107 |
| Total Labor Force 22 to 24, Unemployed, Female      | B23001_108 |
| Total Labor Force 25 to 29, Female                  | B23001_110 |
| Total Labor Force 25 to 29, In Armed Forces, Female | B23001_112 |
| Total Labor Force 25 to 29, Employed, Female        | B23001_114 |
| Total Labor Force 25 to 29, Unemployed, Female      | B23001_115 |
| Total Labor Force 30 to 34, Female                  | B23001_117 |
| Total Labor Force 30 to 34, In Armed Forces, Female | B23001_119 |
| Total Labor Force 30 to 34, Employed, Female        | B23001_121 |
| Total Labor Force 30 to 34, Unemployed, Female      | B23001_122 |
| Total Labor Force 35 to 44, Female                  | B23001_124 |
| Total Labor Force 35 to 44, In Armed Forces, Female | B23001_126 |
| Total Labor Force 35 to 44, Employed, Female        | B23001_128 |
| Total Labor Force 35 to 44, Unemployed, Female      | B23001_129 |
| Total Labor Force 45 to 54, Female                  | B23001_131 |
| Total Labor Force 45 to 54, In Armed Forces, Female | B23001_133 |
| Total Labor Force 45 to 54, Employed, Female        | B23001_135 |
| Total Labor Force 45 to 54, Unemployed, Female      | B23001_136 |
| Total Labor Force 55 to 59, Female                  | B23001_138 |
| Total Labor Force 55 to 59, In Armed Forces, Female | B23001_140 |
| Total Labor Force 55 to 59, Employed, Female        | B23001_142 |
| Total Labor Force 55 to 59, Unemployed, Female      | B23001_143 |
| Total Labor Force 60 to 61, Female                  | B23001_145 |
| Total Labor Force 60 to 61, In Armed Forces, Female | B23001_147 |
| Total Labor Force 60 to 61, Employed, Female        | B23001_149 |
| Total Labor Force 60 to 61, Unemployed, Female      | B23001_150 |
| Total Labor Force 62 to 64, Female                  | B23001_152 |
| Total Labor Force 62 to 64, In Armed Forces, Female | B23001_154 |
| Total Labor Force 62 to 64, Employed, Female        | B23001_156 |
| Total Labor Force 62 to 64, Unemployed, Female      | B23001_157 |
| Total Labor Force 65 to 69, Female                  | B23001_159 |
| Total Labor Force 65 to 69, Employed, Female        | B23001_161 |
| Total Labor Force 65 to 69, Unemployed, Female      | B23001_162 |
| Total Labor Force 70 to 74, Female                  | B23001_164 |
| Total Labor Force 70 to 74, Employed, Female        | B23001_166 |
| Total Labor Force 70 to 74, Unemployed, Female      | B23001_167 |
| Total Labor Force Over 75, Female                   | B23001_169 |
| Total Labor Force Over 75, Employed, Female         | B23001_171 |
| Total Labor Force Over 75, Unemployed, Female       | B23001_172 |
